print("Welcome to the Band Name Generator.")
city = input("Which city did you grow up in?\n")
print(city)
pet = input("What is the name of a pet?\n")
print(pet)
print("Your band name could be: " + city + " " + pet)